### PR TITLE
Breaking

### PR DESCRIPTION
**Pull request by notlee**
See https://github.com/Financial-Times/o-fonts/issues/94

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-fonts bundle size difference from 3.3.2 to 8d2ecad7b3b6bb402a5d65570e309159058c7b8a
No bundle size differences found.

**Comment by notlee** [comment]
Ooops, this was supposed to remain a draft pr

**Comment by origamiserviceuser** [comment]
o-fonts bundle size difference from 3.3.2 to 44a1f15914b52ee77d9af1cd073dfb8da5e9fdc8
css, master: 0.25kb increase (0.01kb/gzip)
An insignificant difference was also found for: css (internal), css (whitelabel)

**Comment by origamiserviceuser** [comment]
o-fonts bundle size difference from 3.3.2 to 619597dd504d347808e18cd65364ab3b26ab85f6
css, master: 0.25kb increase (0.01kb/gzip)
An insignificant difference was also found for: css (internal), css (whitelabel)

**Pull request merged**
