### PR TITLE
Concat `font-suffix` properly

### PR DESCRIPTION
**Pull request by ironsidevsquincy**
Before:

```
"Weight"Style
```

After:

```
WeightStyle
```

### CODE REVIEW

**Comment by AlbertoElias** [comment]
Can you test if there are differences between the new and previous version of libsass to confirm it's related?

**Comment by ironsidevsquincy** [comment]
Works as previously expected with node-sass@v3.3.3, so guessing something changed in lib-sass@v3.3.0

**Comment by AlbertoElias** [comment]
Can you try with node-sass 3.4.1, it updates to a patch release in libsass which seems to have fixed this issue: https://github.com/sass/libsass/issues/1624

**Comment by ironsidevsquincy** [comment]
That's the version obt is currently using - issue is present in it

**Comment by AlbertoElias** [comment]
Ok, thanks. Could you update the travis file so it passes the tests to the latest recommended config file: http://origami.ft.com/docs/component-spec/modules/#continuous-integration

**Pull request merged**
