### PR TITLE
Remove deprecated variables (breaking change)

### PR DESCRIPTION
**Pull request by keirog**

### CODE REVIEW

**Comment by AlbertoElias** [comment]
Could you update the travis file to something like this one please? https://github.com/Financial-Times/o-tabs/blob/master/.travis.yml

**Comment by kaelig** [comment]
This commit history and diff is really weird. :-1: until the changes are clearly marked.

Can you please branch out from v2, then apply 5abdbf9ef048f0070a9a42f2f80f37e8d2f5afa3 and then make a new PR?

**Comment by keirog** [comment]
@kaelig I don't understand… they're your commits!

**Comment by kaelig** [comment]
Sorry I wasn't clear previously. I was not asking for a the v2 branch to be merged into master, but for your commit to be merged into v2. Does that make sense? Hence the confusion

**Comment by keirog** [comment]
Ah sorry! Yep, clear now

**Pull request closed without merging**
