### PR TITLE
Output FinancierDisplayWeb Variable Font

### PR DESCRIPTION
**Pull request by notlee**
If any FinancierDisplayWeb font variant is included also output
the equivalent variable FinancierDisplayWeb font once. The variants
of FinancierDisplayWeb specifically requested may be used as
fallback fonts for older browsers, whilst the variable font may be
used to display a greater number of font variants.

`oFontsVariantExists` does not yet account for variable fonts,
therefore they are effectively not usable since `o-typography`,
which checks a font variant exists before outputting typographic
styles, will continue to only allow styles supported by
non-variable fonts. `oFontsVariantExists` should perhaps be
deprecated in favour of `oFontsVariantAllowed`, that includes a
set of variants which may be used (`FinancierDisplayWeb`
supports 500 weights, we'd rather users include a limited set for
design consistency). That's blocked until the design team decide
what variants to allow.

Depends on: https://github.com/Financial-Times/o-fonts-assets/pull/53
Relates to: https://github.com/Financial-Times/origami/pull/75

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-fonts bundle size difference from 4.4.1 to bfecdf78873d8e21f70e5a8917b5a13b59d359cd
css, master: 0.38kb increase (0.09kb/gzip)
An insignificant difference was also found for: css (internal), css (whitelabel)

**Comment by origamiserviceuser** [comment]
o-fonts bundle size difference from 4.4.1 to 3d5da0800c2542a2dedd16110b02622de71a68e1
css, master: 0.48kb increase (0.08kb/gzip)
An insignificant difference was also found for: css (internal), css (whitelabel)

**Comment by JakeChampion** [comment]
We can do the o-typography work inside this pull-request :D
https://github.com/Financial-Times/o-typography/pull/292

**Comment by chee** [comment]
https://github.com/Financial-Times/origami/pull/227

**Pull request closed without merging**
